fix: check if the 'resource' exist, instead of check if 'file' exists on update, patch and compare cmds

diff --git a/shell/secretctl b/shell/secretctl
--- a/shell/secretctl
+++ b/shell/secretctl
@@ -508,7 +508,7 @@ function update_secret() {
     SECRET_NAME="$1"
     SECRET_FILE="$2"
 
-    [ ! -f "${SECRET_FILE}" ] && logger "WARN" "create_secret" "file not found: ${SECRET_FILE}" && exit 1
+    [ ! -e "${SECRET_FILE}" ] && logger "WARN" "create_secret" "file not found: ${SECRET_FILE}" && exit 1
     [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "update_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
     if [[ "${DRY_RUN}" == "true" ]]; then
@@ -531,7 +531,7 @@ function patch_secret() {
     SECRET_NAME="$1"
     PATCH_FILE="$2"
 
-    [ ! -f "${PATCH_FILE}" ] && logger "WARN" "patch_secret" "File not found: ${PATCH_FILE}" && exit 1
+    [ ! -e "${PATCH_FILE}" ] && logger "WARN" "patch_secret" "File not found: ${PATCH_FILE}" && exit 1
     [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "patch_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
     OLD_CONTENT="/tmp/${SECRET_NAME}.old"
@@ -655,7 +655,7 @@ function compare_secret() {
     SECRET_NAME="$1"
     COMPARE_FILE="$2"
 
-    [ ! -f "${COMPARE_FILE}" ] && logger "WARN" "create_secret" "file not found: ${COMPARE_FILE}" && exit 1
+    [ ! -e "${COMPARE_FILE}" ] && logger "WARN" "create_secret" "file not found: ${COMPARE_FILE}" && exit 1
     [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "update_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
     SECRET_CONTENT=$(get_secret "${SECRET_NAME}")
