feat: replace echo cmds with logging

diff --git a/shell/secretctl b/shell/secretctl
--- a/shell/secretctl
+++ b/shell/secretctl
@@ -166,7 +166,7 @@ function parse_commands() {
             search)
                 if [ $# -ne 1 ]; then
                     echo "Please, provide the: pattern"
-                    echo "example: secretctl search 'app-(dev|stg|prd|sdx)'"
+                    echo "Example: secretctl search 'app-(dev|stg|prd|sdx)'"
                     usage
                 fi
 
@@ -177,7 +177,7 @@ function parse_commands() {
             create)
                 if [ $# -ne 2 ]; then
                     echo "Please, provide the: secret_name and secret_file"
-                    echo "example: secretctl create app-dev /tmp/secrets/app-dev-v1.env"
+                    echo "Example: secretctl create app-dev /tmp/secrets/app-dev-v1.env"
                     usage
                 fi
 
@@ -189,7 +189,7 @@ function parse_commands() {
             get)
                 if [ $# -ne 1 ]; then
                     echo "Please, provide the: secret_name"
-                    echo "example: secretctl get app-dev"
+                    echo "Example: secretctl get app-dev"
                     usage
                 fi
 
@@ -209,7 +209,7 @@ function parse_commands() {
 
                 if [ $# -ne "${MAX_ARGS}" ]; then
                     echo "Please, provide the: secret_name and secret_file"
-                    echo "example: secretctl update app-dev /tmp/secrets/app-dev-v2.env"
+                    echo "Example: secretctl update app-dev /tmp/secrets/app-dev-v2.env"
                     usage
                 fi
 
@@ -239,7 +239,7 @@ function parse_commands() {
 
                 if [ $# -ne "${MAX_ARGS}" ]; then
                     echo "Please, provide the: secret_name and patch_file"
-                    echo "example: secretctl patch app-dev /tmp/secrets/app-dev-v2.patch"
+                    echo "Example: secretctl patch app-dev /tmp/secrets/app-dev-v2.patch"
                     usage
                 fi
 
@@ -260,7 +260,7 @@ function parse_commands() {
             disable)
                 if [ $# -ne 2 ]; then
                     echo "Please, provide the: secret_name and secret_version"
-                    echo "example: secretctl disable app-dev 2"
+                    echo "Example: secretctl disable app-dev 2"
                     usage
                 fi
 
@@ -272,7 +272,7 @@ function parse_commands() {
             enable)
                 if [ $# -ne 2 ]; then
                     echo "Please, provide the: secret_name and secret_version"
-                    echo "example: secretctl enable app-dev 1"
+                    echo "Example: secretctl enable app-dev 1"
                     usage
                 fi
 
@@ -284,7 +284,7 @@ function parse_commands() {
             delete)
                 if [ $# -ne 1 ]; then
                     echo "Please, provide the: secret_name"
-                    echo "example: secretctl delete app-dev"
+                    echo "Example: secretctl delete app-dev"
                     usage
                 fi
 
@@ -295,7 +295,7 @@ function parse_commands() {
             diff)
                 if [ $# -ne 2 ]; then
                     echo "Please, provide the: secret_1 and secret_2"
-                    echo "example: secretctl diff /tmp/secrets/app-dev-v1.env /tmp/secrets/app-dev-v2.env"
+                    echo "Example: secretctl diff /tmp/secrets/app-dev-v1.env /tmp/secrets/app-dev-v2.env"
                     usage
                 fi
 
@@ -344,13 +344,13 @@ function diff_content() {
         SECRET_1_KEYS=$(echo "${SECRET_1_CONTENT}" | cut -d "=" -f1 | uniq -d)
         SECRET_2_KEYS=$(echo "${SECRET_2_CONTENT}" | cut -d "=" -f1 | uniq -d)
         if [[ $(echo "${SECRET_1_KEYS}" | wc -l) -eq 0 ]] && [[ $(echo "${SECRET_2_KEYS}" | wc -l) -eq 0 ]]; then
-            echo "[FAIL] - There are some duplicated keys in both secret-1 and secret-2:"
+            loggger "WARN" "check_duplicated_keys" "[FAIL] - There are some duplicated keys in both secret-1 and secret-2"
             echo -e "\n----- secret-1:\n${SECRET_1_KEYS}\n"
             echo -e "\n----- secret-2:\n${SECRET_2_KEYS}\n"
             exit 0
         fi
-        [[ $(echo "${SECRET_1_KEYS}" | sed '/^$/d' | wc -l) -gt 1 ]] && echo -e "[FAIL] - There are some duplicated keys on secret-1:\n${SECRET_1_KEYS}" && exit 0
-        [[ $(echo "${SECRET_2_KEYS}" | sed '/^$/d' | wc -l) -gt 1 ]] && echo -e "[FAIL] - There are some duplicated keys on secret-2:\n${SECRET_1_KEYS}" && exit 0
+        [[ $(echo "${SECRET_1_KEYS}" | sed '/^$/d' | wc -l) -gt 1 ]] && logger "WARN" "check_missing_keys" "[FAIL] - There are some duplicated keys on secret-1:\n${SECRET_1_KEYS}" && exit 0
+        [[ $(echo "${SECRET_2_KEYS}" | sed '/^$/d' | wc -l) -gt 1 ]] && logger "WARN" "check_missing_keys" "[FAIL] - There are some duplicated keys on secret-2:\n${SECRET_1_KEYS}" && exit 0
     }
 
     function check_missing_keys() {
@@ -372,7 +372,7 @@ function diff_content() {
             done
         fi
         [ "${MISSING_KEYS_COUNT}" -eq 0 ] && MISSING_KEYS_CHECK=1 || MISSING_KEYS_CHECK=0
-        [[ "${MISSING_KEYS_CHECK}" -eq 0 ]] && echo -e "[FAIL] - There are some missing keys:\n${UNMATCHED_FIELDS@}" && exit 0
+        [[ "${MISSING_KEYS_CHECK}" -eq 0 ]] && logger "WARN" "check_missing_keys" "[FAIL] - There are some missing keys:\n${UNMATCHED_FIELDS@}" && exit 0
     }
 
     function check_key_values() {
@@ -450,8 +450,9 @@ function create_secret() {
     SECRET_NAME="$1"
     SECRET_FILE="$2"
 
-    [ ! -f "${SECRET_FILE}" ] && echo "file not found: ${SECRET_FILE}" && exit 1
+    [ ! -f "${SECRET_FILE}" ] && logger "WARN" "create_secret" "file not found: ${SECRET_FILE}" && exit 1
 
+    logger "INFO" "create_secret" "Creating secret: ${SECRET_NAME}"
     gcloud secrets create "${SECRET_NAME}" \
         --data-file="${SECRET_FILE}" \
         --project="${GCP_PROJECT_ID}" &> /dev/null
@@ -461,7 +462,7 @@ function create_secret() {
 function get_secret() {
     SECRET_NAME="$1"
 
-    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
+    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "get_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
     gcloud secrets versions access latest \
         --secret="${SECRET_NAME}" \
@@ -472,10 +473,10 @@ function update_secret() {
     SECRET_NAME="$1"
     SECRET_FILE="$2"
 
-    [ ! -f "${SECRET_FILE}" ] && echo "file not found: ${SECRET_FILE}" && exit 1
-    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
+    [ ! -f "${SECRET_FILE}" ] && logger "WARN" "create_secret" "file not found: ${SECRET_FILE}" && exit 1
+    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "update_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
-    echo "updating..."
+    logger "INFO" "update_secret" "Updating the secret: ${SECRET_NAME}"
     gcloud secrets versions add "${SECRET_NAME}" \
         --data-file="${SECRET_FILE}" \
         --project="${GCP_PROJECT_ID}" &> /dev/null
@@ -486,23 +487,26 @@ function patch_secret() {
     SECRET_NAME="$1"
     PATCH_FILE="$2"
 
-    [ ! -f "${PATCH_FILE}" ] && echo "file not found: ${PATCH_FILE}" && exit 1
-    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
+    [ ! -f "${PATCH_FILE}" ] && logger "WARN" "patch_secret" "file not found: ${PATCH_FILE}" && exit 1
+    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "patch_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
     OLD_CONTENT="/tmp/${SECRET_NAME}.old"
     TMP_CONTENT="/tmp/${SECRET_NAME}.tmp"
     NEW_CONTENT="/tmp/${SECRET_NAME}.new"
 
-    # 1. get secret current secret content 
+    # 1. get the current secret content
+    logger "DEBUG" "patch_secret" "Getting the current secret content"
     get_secret "${SECRET_NAME}" > "${OLD_CONTENT}"
 
     # 2. get keys that are in both of the new and old secret content
+    logger "DEBUG" "patch_secret" "Getting keys that are in both of the new and old secret content"
     for line in $(cat "${PATCH_FILE}"); do
         line_key=$(echo "${line}" | cut -d"=" -f1)
         grep "${line_key}" "${OLD_CONTENT}" >> "${TMP_CONTENT}"
     done
 
     # 3. replace old values with new values
+    logger "DEBUG" "patch_secret" "Replacing old values with new values"
     cp "${TMP_CONTENT}" "${OLD_CONTENT}"
     for line in $(cat "${TMP_CONTENT}"); do
         line_key=$(echo "${line}" | cut -d"=" -f1)
@@ -510,8 +514,9 @@ function patch_secret() {
     done
 
     # 4. diff old and new secret content
+    logger "DEBUG" "patch_secret" "Comparing old and new secret contents"
     diff_content "${OLD_CONTENT}" "${NEW_CONTENT}" > /dev/null
-    [ $? -eq 0 ] && echo "No changes to be done here" && exit 0
+    [ $? -eq 0 ] && logger "WARN" "patch_secret" "No changes to be done here" && exit 0
 
     # 5. update the secret
     update_secret "${SECRET_NAME}" "${NEW_CONTENT}"
@@ -524,12 +529,12 @@ function patch_secret() {
 
 function disable_secret() {
     SECRET_NAME=$1
-    PREVIOUS_VERSION=$2
+    SECRET_VERSION=$2
 
     [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
 
-    echo "disabling..."
-    gcloud secrets versions disable "${PREVIOUS_VERSION}" \
+    logger "INFO" "disable_secret" "Disabling secret version: ${SECRET_NAME}[${SECRET_VERSION}]"
+    gcloud secrets versions disable "${SECRET_VERSION}" \
         --secret="${SECRET_NAME}" \
         --project="${GCP_PROJECT_ID}" &> /dev/null
     logger "INFO" "disable_secret" "Secret version disabled"
@@ -537,12 +542,12 @@ function disable_secret() {
 
 function enable_secret() {
     SECRET_NAME=$1
-    PREVIOUS_VERSION=$2
+    SECRET_VERSION=$2
 
     [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
 
-    echo "disabling..."
-    gcloud secrets versions enable "${PREVIOUS_VERSION}" \
+    logger "INFO" "enable_secret" "Enabling secret version: ${SECRET_NAME}[${SECRET_VERSION}]"
+    gcloud secrets versions enable "${SECRET_VERSION}" \
         --secret="${SECRET_NAME}" \
         --project="${GCP_PROJECT_ID}" &> /dev/null
     logger "INFO" "enable_secret" "Secret version enabled"
@@ -553,6 +558,7 @@ function delete_secret() {
 
     [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
 
+    logger "INFO" "delete_secret" "Deleting secret: ${SECRET_NAME}"
     yes | gcloud secrets delete "${SECRET_NAME}" \
         --project="${GCP_PROJECT_ID}" &> /dev/null
     logger "INFO" "delete_secret" "Secret deleted"
