fix: SC2317 and SC2086

diff --git a/shell/secretctl b/shell/secretctl
--- a/shell/secretctl
+++ b/shell/secretctl
@@ -354,7 +354,6 @@ function parse_commands() {
             ;;
             *)
                 usage
-                break
             ;;
         esac
     done
@@ -369,8 +368,8 @@ function diff_content() {
     SECRET_2_CONTENT=$2
 
     function check_content_type() {
-        [ $(echo "${SECRET_1_CONTENT}" | grep -cE "[A-Z_0-9]=.*") -ge 1 ] && SECRET_1_CONTENT_TYPE="dotenv"
-        [ $(echo "${SECRET_2_CONTENT}" | grep -cE "[A-Z_0-9]=.*") -ge 1 ] && SECRET_2_CONTENT_TYPE="dotenv"
+        [ "$(echo "${SECRET_1_CONTENT}" | grep -cE "[A-Z_0-9]=.*")" -ge 1 ] && SECRET_1_CONTENT_TYPE="dotenv"
+        [ "$(echo "${SECRET_2_CONTENT}" | grep -cE "[A-Z_0-9]=.*")" -ge 1 ] && SECRET_2_CONTENT_TYPE="dotenv"
         [[ "${SECRET_1_CONTENT_TYPE}" == "${SECRET_1_CONTENT_TYPE}" ]] && SECRET_TYPE="dotenv"
         [[ "${SECRET_TYPE}" == dotenv ]] && SECRET_TYPE_CHECK=1 || SECRET_TYPE_CHECK=0
         [[ "${SECRET_TYPE_CHECK}" -eq 0 ]] && echo "[FAIL] - The secret types dont match: secret-1[${SECRET_1_CONTENT_TYPE}] and secret-2[${SECRET_2_CONTENT_TYPE}]" && exit 0
@@ -503,7 +502,7 @@ function create_secret() {
 function get_secret() {
     SECRET_NAME="$1"
 
-    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "get_secret" "Secret not found: ${SECRET_NAME}" && exit 1
+    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && logger "WARN" "get_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
     gcloud secrets versions access latest \
         --secret="${SECRET_NAME}" \
@@ -515,7 +514,7 @@ function update_secret() {
     SECRET_FILE="$2"
 
     [ ! -e "${SECRET_FILE}" ] && logger "WARN" "create_secret" "file not found: ${SECRET_FILE}" && exit 1
-    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "update_secret" "Secret not found: ${SECRET_NAME}" && exit 1
+    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && logger "WARN" "update_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
     if [[ "${DRY_RUN}" == "true" ]]; then
         logger "INFO" "create_secret" "DRY_RUN: updating secret ${SECRET_NAME}:"
@@ -538,7 +537,7 @@ function patch_secret() {
     PATCH_FILE="$2"
 
     [ ! -e "${PATCH_FILE}" ] && logger "WARN" "patch_secret" "File not found: ${PATCH_FILE}" && exit 1
-    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "patch_secret" "Secret not found: ${SECRET_NAME}" && exit 1
+    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && logger "WARN" "patch_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
     OLD_CONTENT="/tmp/${SECRET_NAME}.old"
     NEW_CONTENT="/tmp/${SECRET_NAME}.new"
@@ -589,7 +588,7 @@ function disable_secret() {
     SECRET_NAME=$1
     SECRET_VERSION=$2
 
-    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
+    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
 
     logger "INFO" "disable_secret" "Disabling secret version: ${SECRET_NAME}[${SECRET_VERSION}]"
     gcloud secrets versions disable "${SECRET_VERSION}" \
@@ -602,7 +601,7 @@ function enable_secret() {
     SECRET_NAME=$1
     SECRET_VERSION=$2
 
-    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
+    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
 
     logger "INFO" "enable_secret" "Enabling secret version: ${SECRET_NAME}[${SECRET_VERSION}]"
     gcloud secrets versions enable "${SECRET_VERSION}" \
@@ -614,7 +613,7 @@ function enable_secret() {
 function delete_secret() {
     SECRET_NAME=$1
 
-    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
+    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
 
     logger "INFO" "delete_secret" "Deleting secret: ${SECRET_NAME}"
     yes | gcloud secrets delete "${SECRET_NAME}" \
@@ -626,8 +625,8 @@ function diff_secrets() {
     SECRET_NAME_1=$1
     SECRET_NAME_2=$2
 
-    [ $(check_secret_exists "${SECRET_NAME_1}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME_1}" && exit 1
-    [ $(check_secret_exists "${SECRET_NAME_2}") -eq 0 ] && echo "Secret not found: ${SECRET_NAME_2}" && exit 1
+    [ "$(check_secret_exists "${SECRET_NAME_1}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME_1}" && exit 1
+    [ "$(check_secret_exists "${SECRET_NAME_2}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME_2}" && exit 1
 
     SECRET_1_CONTENT=$(get_secret "${SECRET_NAME_1}" | sort)
     SECRET_2_CONTENT=$(get_secret "${SECRET_NAME_2}" | sort)
@@ -662,7 +661,7 @@ function compare_secret() {
     COMPARE_FILE="$2"
 
     [ ! -e "${COMPARE_FILE}" ] && logger "WARN" "create_secret" "file not found: ${COMPARE_FILE}" && exit 1
-    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "update_secret" "Secret not found: ${SECRET_NAME}" && exit 1
+    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && logger "WARN" "update_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
     SECRET_CONTENT=$(get_secret "${SECRET_NAME}")
     FILE_CONTENT=$(cat "${COMPARE_FILE}")
