feat: add delete-fields cmd

diff --git a/shell/secretctl b/shell/secretctl
--- a/shell/secretctl
+++ b/shell/secretctl
@@ -114,6 +114,9 @@ function usage() {
 
         compare [SECRET_NAME] [COMPARE_FILE]
             Compare secret and file contents
+
+        delete-fields [SECRET_NAME] [FIELDS]
+            Delete comma separated secret fields
             
 
     EXAMPLES:
@@ -129,6 +132,7 @@ function usage() {
         secretctl diff app-dev app-stg
         secretctl find 'app-(dev|stg)' MONGODB
         secretctl compare app-dev /tmp/secrets/app-dev-v2.compare
+        secretctl delete-fields app-dev FIELD1,FIELD2,FIELD3
     "
     exit 0
 }
@@ -356,6 +360,18 @@ function parse_commands() {
                 SECRET_NAME="$1"
                 COMPARE_FILE="$2"
                 compare_secret "${SECRET_NAME}" "${COMPARE_FILE}"
+                break
+            ;;
+            delete-fields)
+                if [ $# -ne 2 ]; then
+                    echo "Please, provide the: secret_name and fields"
+                    echo "Example: secretctl compare app-dev FIELD1,FIELD2,FIELD3"
+                    usage
+                fi
+
+                SECRET_NAME="$1"
+                FIELDS_TO_DELETE="$2"
+                delete_fields "${SECRET_NAME}" "${FIELDS_TO_DELETE}"
                 break
             ;;
             *)
@@ -675,6 +691,19 @@ function compare_secret() {
     diff_content "${SECRET_CONTENT}" "${FILE_CONTENT}"
 }
 
+function delete_fields() {
+    SECRET_NAME="$1"
+    FIELDS_TO_DELETE="$2"
+
+    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && logger "WARN" "delete_fields" "Secret not found: ${SECRET_NAME}" && exit 1
+        
+    logger "INFO" "delete_fields" "Deleting fields: ${SECRET_NAME}"
+    get_secret "${SECRET_NAME}" > "/tmp/${SECRET_NAME}.old"
+    IGNORE_LINES_PATTERN=$(echo "${FIELDS_TO_DELETE}" | tr "," "|")
+    sed -E "/${IGNORE_LINES_PATTERN}/d" "/tmp/${SECRET_NAME}.old" > "/tmp/${SECRET_NAME}.new"
+    update_secret "${SECRET_NAME}" "/tmp/${SECRET_NAME}.new"
+    logger "INFO" "delete_fields" "Fields deleted"
+}
 
 
 ## ---------- MAIN
