refact: refactor patch cmd logic

diff --git a/shell/secretctl b/shell/secretctl
--- a/shell/secretctl
+++ b/shell/secretctl
@@ -495,44 +495,43 @@ function patch_secret() {
     SECRET_NAME="$1"
     PATCH_FILE="$2"
 
-    [ ! -f "${PATCH_FILE}" ] && logger "WARN" "patch_secret" "file not found: ${PATCH_FILE}" && exit 1
+    [ ! -f "${PATCH_FILE}" ] && logger "WARN" "patch_secret" "File not found: ${PATCH_FILE}" && exit 1
     [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "patch_secret" "Secret not found: ${SECRET_NAME}" && exit 1
 
     OLD_CONTENT="/tmp/${SECRET_NAME}.old"
-    TMP_CONTENT="/tmp/${SECRET_NAME}.tmp"
     NEW_CONTENT="/tmp/${SECRET_NAME}.new"
+    rm -f "${OLD_CONTENT}" "${NEW_CONTENT}"
 
-    # 1. get the current secret content
     logger "DEBUG" "patch_secret" "Getting the current secret content"
     get_secret "${SECRET_NAME}" > "${OLD_CONTENT}"
 
-    # 2. get keys that are in both of the new and old secret content
-    logger "DEBUG" "patch_secret" "Getting keys that are in both of the new and old secret content"
-    for line in $(cat "${PATCH_FILE}"); do
-        line_key=$(echo "${line}" | cut -d"=" -f1)
-        grep "${line_key}" "${OLD_CONTENT}" >> "${TMP_CONTENT}"
-    done
+    cp "${OLD_CONTENT}" "${NEW_CONTENT}"
 
-    # 3. replace old values with new values
-    logger "DEBUG" "patch_secret" "Replacing old values with new values"
-    cp "${TMP_CONTENT}" "${OLD_CONTENT}"
-    for line in $(cat "${TMP_CONTENT}"); do
+    logger "DEBUG" "patch_secret" "Processing patch file"
+    while IFS= read -r line; do
+        if [[ "${line}" =~ ^- ]]; then
+            line_key=$(echo "${line}" | cut -d"-" -f2 | cut -d "=" -f1)            
+            sed -i "/^${line_key}=.*/d" "${NEW_CONTENT}"
+        else
         line_key=$(echo "${line}" | cut -d"=" -f1)
-        sed -i "s|${line_key}=(.*)|${line}|g" "${NEW_CONTENT}"
-    done
+            if grep -q "^${line_key}=" "${NEW_CONTENT}"; then
+                sed -i "s|^${line_key}=.*|${line}|g" "${NEW_CONTENT}"
+            else
+                echo "${line}" >> "${NEW_CONTENT}"
+            fi
+        fi
+    done < "${PATCH_FILE}"
 
-    # 4. diff old and new secret content
     logger "DEBUG" "patch_secret" "Comparing old and new secret contents"
-    diff_content "${OLD_CONTENT}" "${NEW_CONTENT}" > /dev/null
-    [ $? -eq 0 ] && logger "WARN" "patch_secret" "No changes to be done here" && exit 0
-
-    # 5. update the secret
+    if diff -q "${OLD_CONTENT}" "${NEW_CONTENT}" >/dev/null; then
+        logger "WARN" "patch_secret" "No changes to be done here"
+        exit 0
+    else
+        logger "DEBUG" "patch_secret" "Updating secret with new content"
     update_secret "${SECRET_NAME}" "${NEW_CONTENT}"
+    fi
 
-    # 6. cleanup
-    rm -f "/tmp/${SECRET_NAME}.old"
-    rm -f "/tmp/${SECRET_NAME}.tmp"
-    rm -f "/tmp/${SECRET_NAME}.new"
+    rm -f "${OLD_CONTENT}" "${NEW_CONTENT}"
 }
 
 function disable_secret() {
