feat: just check if secret exist when the --check-secret flag is present

diff --git a/shell/secretctl b/shell/secretctl
--- a/shell/secretctl
+++ b/shell/secretctl
@@ -63,8 +63,10 @@ function usage() {
 
     USAGE: secretctl [OPTIONS] [COMMAND OPTIONS]...
 
-    OPTIONS:
+    GLOBAL OPTIONS:
         -p, --project <gcp_project_id>   Specify the GCP project ID.  [optional]
+        --dry-run                        Simulate the exection, but just show the results without execute anything
+        --check-secret                   Check if the secret exists; Do not works with commands: help, list, create, search, find, diff
     
     NOTES:
         [1] If the option -p or --project not set, the current GCP project ID will be used.
@@ -179,6 +181,18 @@ function parse_commands() {
             set -- "${NEW_ARGS}"
         else
             export DRY_RUN=false
+        fi
+
+        if [[ $(echo "$@" | grep -cE '\--check-secret( |$)') -eq 1 ]]; then
+            if [[ ! "${COMMAND}" =~ help|list|create|search|find|diff ]]; then
+                SECRET_NAME="$1"
+                [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
+            elif [[ "${COMMAND}" == diff ]]; then
+                SECRET_NAME_1="$1"
+                SECRET_NAME_2="$2"
+                [ "$(check_secret_exists "${SECRET_NAME_1}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME_1}" && exit 1
+                [ "$(check_secret_exists "${SECRET_NAME_2}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME_2}" && exit 1
+            fi
         fi
 
         case "${COMMAND}" in
@@ -523,9 +537,6 @@ function create_secret() {
 
 function get_secret() {
     SECRET_NAME="$1"
-
-    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && logger "WARN" "get_secret" "Secret not found: ${SECRET_NAME}" && exit 1
-
     gcloud secrets versions access latest \
         --secret="${SECRET_NAME}" \
         --project="${GCP_PROJECT_ID}"
@@ -536,8 +547,6 @@ function update_secret() {
     SECRET_FILE="$2"
 
     [ ! -e "${SECRET_FILE}" ] && logger "WARN" "create_secret" "file not found: ${SECRET_FILE}" && exit 1
-    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && logger "WARN" "update_secret" "Secret not found: ${SECRET_NAME}" && exit 1
-
     if [[ "${DRY_RUN}" == "true" ]]; then
         logger "INFO" "create_secret" "DRY_RUN: updating secret ${SECRET_NAME}:"
         echo "----- OLD CONTENT"
@@ -559,8 +568,6 @@ function patch_secret() {
     PATCH_FILE="$2"
 
     [ ! -e "${PATCH_FILE}" ] && logger "WARN" "patch_secret" "File not found: ${PATCH_FILE}" && exit 1
-    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && logger "WARN" "patch_secret" "Secret not found: ${SECRET_NAME}" && exit 1
-
     OLD_CONTENT="/tmp/${SECRET_NAME}.old"
     NEW_CONTENT="/tmp/${SECRET_NAME}.new"
     rm -f "${OLD_CONTENT}" "${NEW_CONTENT}"
@@ -610,8 +617,6 @@ function disable_secret() {
     SECRET_NAME=$1
     SECRET_VERSION=$2
 
-    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
-
     logger "INFO" "disable_secret" "Disabling secret version: ${SECRET_NAME}[${SECRET_VERSION}]"
     gcloud secrets versions disable "${SECRET_VERSION}" \
         --secret="${SECRET_NAME}" \
@@ -623,8 +628,6 @@ function enable_secret() {
     SECRET_NAME=$1
     SECRET_VERSION=$2
 
-    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
-
     logger "INFO" "enable_secret" "Enabling secret version: ${SECRET_NAME}[${SECRET_VERSION}]"
     gcloud secrets versions enable "${SECRET_VERSION}" \
         --secret="${SECRET_NAME}" \
@@ -635,8 +638,6 @@ function enable_secret() {
 function delete_secret() {
     SECRET_NAME=$1
 
-    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME}" && exit 1
-
     logger "INFO" "delete_secret" "Deleting secret: ${SECRET_NAME}"
     yes | gcloud secrets delete "${SECRET_NAME}" \
         --project="${GCP_PROJECT_ID}" &> /dev/null
@@ -646,9 +647,6 @@ function delete_secret() {
 function diff_secrets() {
     SECRET_NAME_1=$1
     SECRET_NAME_2=$2
-
-    [ "$(check_secret_exists "${SECRET_NAME_1}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME_1}" && exit 1
-    [ "$(check_secret_exists "${SECRET_NAME_2}")" -eq 0 ] && echo "Secret not found: ${SECRET_NAME_2}" && exit 1
 
     SECRET_1_CONTENT=$(get_secret "${SECRET_NAME_1}" | sort)
     SECRET_2_CONTENT=$(get_secret "${SECRET_NAME_2}" | sort)
@@ -683,8 +681,6 @@ function compare_secret() {
     COMPARE_FILE="$2"
 
     [ ! -e "${COMPARE_FILE}" ] && logger "WARN" "create_secret" "file not found: ${COMPARE_FILE}" && exit 1
-    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && logger "WARN" "update_secret" "Secret not found: ${SECRET_NAME}" && exit 1
-
     SECRET_CONTENT=$(get_secret "${SECRET_NAME}")
     FILE_CONTENT=$(cat "${COMPARE_FILE}")
 
@@ -694,8 +690,6 @@ function compare_secret() {
 function delete_fields() {
     SECRET_NAME="$1"
     FIELDS_TO_DELETE="$2"
-
-    [ "$(check_secret_exists "${SECRET_NAME}")" -eq 0 ] && logger "WARN" "delete_fields" "Secret not found: ${SECRET_NAME}" && exit 1
         
     logger "INFO" "delete_fields" "Deleting fields: ${SECRET_NAME}"
     get_secret "${SECRET_NAME}" > "/tmp/${SECRET_NAME}.old"
