feat: just check if file exist when the --check-file flag is present

diff --git a/shell/secretctl b/shell/secretctl
--- a/shell/secretctl
+++ b/shell/secretctl
@@ -195,6 +195,14 @@ function parse_commands() {
             fi
         fi
 
+        if [[ $(echo "$@" | grep -cE '\--check-file( |$)') -eq 1 ]]; then
+            if [[ "${COMMAND}" =~ create|update|patch|compare ]]; then
+                SECRET_NAME="$1"
+                SECRET_FILE="$2"
+                [ ! -e "${SECRET_FILE}" ] && echo "File not found: ${SECRET_FILE}" && exit 1
+            fi
+        fi
+
         case "${COMMAND}" in
             help)
                 usage
@@ -521,8 +529,6 @@ function create_secret() {
     SECRET_NAME="$1"
     SECRET_FILE="$2"
 
-    [ ! -e "${SECRET_FILE}" ] && logger "WARN" "create_secret" "file not found: ${SECRET_FILE}" && exit 1
-
     if [[ "${DRY_RUN}" == "true" ]]; then
         logger "INFO" "create_secret" "DRY_RUN: creating secret ${SECRET_NAME} with the follow content:"
         cat "${SECRET_FILE}"
@@ -546,7 +552,6 @@ function update_secret() {
     SECRET_NAME="$1"
     SECRET_FILE="$2"
 
-    [ ! -e "${SECRET_FILE}" ] && logger "WARN" "create_secret" "file not found: ${SECRET_FILE}" && exit 1
     if [[ "${DRY_RUN}" == "true" ]]; then
         logger "INFO" "create_secret" "DRY_RUN: updating secret ${SECRET_NAME}:"
         echo "----- OLD CONTENT"
@@ -567,7 +572,6 @@ function patch_secret() {
     SECRET_NAME="$1"
     PATCH_FILE="$2"
 
-    [ ! -e "${PATCH_FILE}" ] && logger "WARN" "patch_secret" "File not found: ${PATCH_FILE}" && exit 1
     OLD_CONTENT="/tmp/${SECRET_NAME}.old"
     NEW_CONTENT="/tmp/${SECRET_NAME}.new"
     rm -f "${OLD_CONTENT}" "${NEW_CONTENT}"
@@ -680,7 +684,6 @@ function compare_secret() {
     SECRET_NAME="$1"
     COMPARE_FILE="$2"
 
-    [ ! -e "${COMPARE_FILE}" ] && logger "WARN" "create_secret" "file not found: ${COMPARE_FILE}" && exit 1
     SECRET_CONTENT=$(get_secret "${SECRET_NAME}")
     FILE_CONTENT=$(cat "${COMPARE_FILE}")
 
