feat: add compare cmd

diff --git a/shell/secretctl b/shell/secretctl
--- a/shell/secretctl
+++ b/shell/secretctl
@@ -103,8 +103,12 @@ function usage() {
         diff [SECRET_NAME_1] [SECRET_NAME_2]
             Compare two secrets
 
-        diff [SECRET_NAME_PATTERN] [DATA_PATTERN]
+        find [SECRET_NAME_PATTERN] [DATA_PATTERN]
             Look for secrets with a specific pattern name and data pattern
+
+        compare [SECRET_NAME] [COMPARE_FILE]
+            Compare secret and file contents
+            
 
     EXAMPLES:
         secretctl list
@@ -118,6 +122,7 @@ function usage() {
         secretctl delete app-dev
         secretctl diff app-dev app-stg
         secretctl find 'app-(dev|stg)' MONGODB
+        secretctl compare app-dev /tmp/secrets/app-dev-v2.compare
     "
     exit 0
 }
@@ -132,7 +137,7 @@ function parse_commands() {
             help)
                 usage
             ;;
-            list|search|create|get|update|patch|disable|enable|delete|diff|find)
+            list|search|create|get|update|patch|disable|enable|delete|diff|find|compare)
                 export COMMAND=$1
                 shift
             ;;
@@ -322,6 +327,18 @@ function parse_commands() {
                 SECRET_NAME_PATTERN="$1"
                 DATA_PATTERN="$2"
                 find_secret "${SECRET_NAME_PATTERN}" "${DATA_PATTERN}"
+                break
+            ;;
+            compare)
+                if [ $# -ne 2 ]; then
+                    echo "Please, provide the: secret_name and compare_file"
+                    echo "Example: secretctl compare app-dev /tmp/secrets/app-dev-v2.compare"
+                    usage
+                fi
+
+                SECRET_NAME="$1"
+                COMPARE_FILE="$2"
+                compare_secret "${SECRET_NAME}" "${COMPARE_FILE}"
                 break
             ;;
             *)
@@ -604,6 +621,19 @@ function find_secret() {
     fi
 
     rm -f /tmp/secret-*.tmp
+}
+
+function compare_secret() {
+    SECRET_NAME="$1"
+    COMPARE_FILE="$2"
+
+    [ ! -f "${COMPARE_FILE}" ] && logger "WARN" "create_secret" "file not found: ${COMPARE_FILE}" && exit 1
+    [ $(check_secret_exists "${SECRET_NAME}") -eq 0 ] && logger "WARN" "update_secret" "Secret not found: ${SECRET_NAME}" && exit 1
+
+    SECRET_CONTENT=$(get_secret "${SECRET_NAME}")
+    FILE_CONTENT=$(cat "${COMPARE_FILE}")
+
+    diff_content "${SECRET_CONTENT}" "${FILE_CONTENT}"
 }
 
 
